apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: net-alanblythe-demo-ingress
  namespace: aks-proxy
  annotations:
    ingress.appscode.com/type: LoadBalancer
spec:
  tls:
  - secretName: net-alanblythe-demo-tls-secret
    hosts:
    - demo.alanblythe.net
  rules:
  - host: demo.alanblythe.net
    http:
      paths:
      - backend:
          serviceName: net-alanblythe-demo
          servicePort: "443"
          headerRules:
          - Host aksproxydemo20190312041303.azurewebsites.net
          backendRules:
          - 'acl response-is-redirect res.hdr(Location) -m found'
          - 'rspirep ^Location:\ (http|https)://(aksproxydemo20190312041303\.azurewebsites\.net)(.*) Location:\ https://demo.alanblythe.net\3 if response-is-redirect'
          - 'http-response set-header X-Added-From-Proxy see we can add headers'
          - 'rspirep ^value1 updatedvalue1'
          - 'rspirep ^value2 updatedvalue2'
          