apiVersion: v1
kind: Namespace
metadata:
  name: aks-proxy
---
apiVersion: v1
kind: Secret
metadata:
  name: acme-account
  namespace: aks-proxy
type: Opaque
stringData:
  ACME_EMAIL: "alanblythe@hotmail.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: voyager-dnsmadeeasy
  namespace: aks-proxy
type: Opaque
stringData:
  DNSMADEEASY_API_KEY: "[fill me in]"
  DNSMADEEASY_API_SECRET: "[fill me in]"
  DNSMADEEASY_SANDBOX: "0"
---
apiVersion: voyager.appscode.com/v1beta1
kind: Certificate
metadata:
  name: net-alanblythe-demo
  namespace: aks-proxy
spec:
  domains:
    - demo.alanblythe.net
  acmeUserSecretName: acme-account
  challengeProvider:
    dns:
      provider: dnsmadeeasy
      credentialSecretName: voyager-dnsmadeeasy
  storage:
    secret:
      name: cert-net-alanblythe-demo
---
apiVersion: v1
kind: Service
metadata:
  name: net-alanblythe-demo
  namespace: aks-proxy
  annotations:
    ingress.appscode.com/use-dns-resolver: "true"
    ingress.appscode.com/dns-resolver-nameservers: '["8.8.8.8:53", "8.8.4.4:53"]'
    ingress.appscode.com/backend-tls: ssl verify none
spec:
  type: ExternalName
  externalName: aksproxydemo20190312062330.azurewebsites.net
---
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: net-alanblythe-demo-ingress
  namespace: aks-proxy
  annotations:
    ingress.appscode.com/keep-source-ip: "true"
    ingress.appscode.com/type: LoadBalancer
spec:
  tls:
  - secretName: cert-net-alanblythe-demo
    hosts:
    - demo.alanblythe.net
  rules:
  - host: demo.alanblythe.net
    http:
      paths:
      - backend:
          serviceName: net-alanblythe-demo
          servicePort: "443"
          headerRules:
          - Host aksproxydemo20190312062330.azurewebsites.net
          backendRules:
          - 'acl response-is-redirect res.hdr(Location) -m found'
          - 'rspirep ^Location:\ (http|https)://(aksproxydemo20190312062330\.azurewebsites\.net)(.*) Location:\ https://demo.alanblythe.net\3 if response-is-redirect'
---
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: stats-ingress
  namespace: aks-proxy
  annotations:
    ingress.appscode.com/type: 'Internal'
    ingress.appscode.com/stats: 'true'
    ingress.appscode.com/stats-port: "56789"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80      
      